return {
  -- {
  --   "yetone/avante.nvim",
  --   -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  --   -- ⚠️ must add this setting! ! !
  --   build = "make",
  --   event = "VeryLazy",
  --   version = false, -- Never set this value to "*"! Never!
  --   ---@module 'avante'
  --   ---@type avante.Config
  --   opts = {
  --     -- add any opts here
  --     provider = "zai", -- Define o z.ai como provedor principal
  --     providers = {
  --       zai = {
  --         __inherited_from = "openai",
  --         endpoint = "https://api.z.ai/api/coding/paas/v4", -- Endpoint específico para coding
  --         api_key_name = "ZAI_API_KEY",
  --         model = "glm-4.7-flash",                          -- Ou o modelo de sua preferência (ex: glm-4.7-flash)
  --       },
  --
  --
  --       claude = {
  --         endpoint = "https://api.z.ai/api/coding/paas/v4",
  --         api_key_name = "ZAI_API_KEY",
  --         timeout = 30000, -- Timeout in milliseconds
  --       },
  --     },                   -- this file can contain specific instructions for your project
  --
  --
  --
  --     auto_suggestions_provider = "zai", -- Define qual IA fará o inline complete
  --
  --     behaviour = {
  --       auto_suggestions = true, -- Ativa o inline completion automático
  --       auto_set_highlight_group = true,
  --       auto_set_keymaps = true,
  --       auto_apply_diff_after_generation = false,
  --       support_paste_from_clipboard = false,
  --     },
  --
  --     -- Configurações visuais e de comportamento das sugestões
  --     suggestions = {
  --       debounce = 300, -- Tempo em ms para esperar antes de pedir a sugestão
  --       throttle = 600,
  --     },
  --   },
  --   config = function(_, opts)
  --     vim.env.ZAI_API_KEY = '32e7582c09f34a0585b11017b7100cad.LMmmU8pvzt8MW9yE'
  --
  --     vim.api.nvim_set_hl(0, "AvanteSuggestion", { fg = "#565f89", italic = true })
  --
  --     require('avante').setup(opts)
  --   end,
  --   dependencies = {
  --     "nvim-lua/plenary.nvim",
  --     "MunifTanjim/nui.nvim",
  --     --- The below dependencies are optional,
  --     "nvim-mini/mini.pick",           -- for file_selector provider mini.pick
  --     "nvim-telescope/telescope.nvim", -- for file_selector provider telescope
  --     "hrsh7th/nvim-cmp",              -- autocompletion for avante commands and mentions
  --     "ibhagwan/fzf-lua",              -- for file_selector provider fzf
  --     "stevearc/dressing.nvim",        -- for input provider dressing
  --     "folke/snacks.nvim",             -- for input provider snacks
  --     "nvim-tree/nvim-web-devicons",   -- or echasnovski/mini.icons
  --     "zbirenbaum/copilot.lua",        -- for providers='copilot'
  --     {
  --       -- support for image pasting
  --       "HakonHarnes/img-clip.nvim",
  --       event = "VeryLazy",
  --       opts = {
  --         -- recommended settings
  --         default = {
  --           embed_image_as_base64 = false,
  --           prompt_for_file_name = false,
  --           drag_and_drop = {
  --             insert_mode = true,
  --           },
  --           -- required for Windows users
  --           use_absolute_path = true,
  --         },
  --       },
  --     },
  --     {
  --       -- Make sure to set this up properly if you have lazy=true
  --       'MeanderingProgrammer/render-markdown.nvim',
  --       opts = {
  --         file_types = { "markdown", "Avante" },
  --       },
  --       ft = { "markdown", "Avante" },
  --     },
  --   },
  -- }
}
